### ISSUE TITLE
Can this be hosted on heroku ?

### ISSUE THREAD

**Issue by Bugaddr** [tejaswinichile/covin#5]

**Comment by tejaswinichile** [comment]
Yes, it does, but you need to add one dyno for the scheduler and do the deployment.

I did it for myself, that app is not useful for others because it contains my personal data regarding the pin codes and updates.

**Comment by Bugaddr** [comment]
> Yes, it does, but you need to add one dyno for the scheduler and do the deployment.
> 
> I did it for myself, that app is not useful for others because it contains my personal data regarding the pin codes and updates.

Thankyou for this information i will try to host it myself
